### ISSUE TITLE
Recommendations on Connecting to HiveMQ or Mosquitto

### ISSUE THREAD

**Issue by mikebru** [jnovack/mqtt-websocket#1]
Thank you for publishing this project, I've been looking for a clean example for a little bit now and this seems to be one of the best! I've been trying to test out the web page by connecting it either to HiveMQ or Mosquitto. I've been running into trouble with the Publish and Subscribe buttons always being grayed out, my assumption is this is because I've not put in the correct connection credentials. 

These are the addresses I've been placing into the connection slot. 
For HiveMQ: ws://broker.mqttdashboard.com:8000/mqtt
For Mosquitto: ws://test.mosquitto.org:8080/mqtt

Any advice you have on how to correctly connect to these brokers would be very much appreciated.

Thank you! 

This is what the webpage looks like. 
![image](https://user-images.githubusercontent.com/32722658/97466265-e78ed200-1910-11eb-8480-ebbf22104bcc.png)

**Comment by jnovack** [comment]
You didn't follow the example for server address.

Even if you did, you cannot connect to an NON-TLS Broker from a TLS webpage.  If you were trying to use this from the README link, you MUST use SSL/TLS. The browser will not let you make an unencrypted connection from an encrypted webpage.
